# Generated by Django 5.2 on 2025-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Stock Normal'), ('BAJO', 'Stock Bajo'), ('AGOTADO', 'Stock Agotado')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor de categorías'), ('ventas', 'Equipo de Ventas')], default='almacen', max_length=20),
        ),
    ]
